server: irc.server.org
port: 6667
use_tls: false
nickname: ebba
username: ebba
realname: Ebba Busch
channels:
- '#kristdemokraterna'
prefix: .
owner_nicks:
- owner
reconnect_delay_secs: 5
request_timeout_secs: 10
plugins:
  chatgpt:
    api_key: ''
    model: gpt-4o-mini
