server: irc.quakenet.org
port: 6667
use_tls: false          # if true, wrap socket with TLS
nickname: ebba2
username: ebba2
realname: ebba2
channels:
  - "#ebba"
prefix: "."
owner_nicks:            # for optional admin-only commands
  - "alx"
reconnect_delay_secs: 5
request_timeout_secs: 10
